### ISSUE TITLE
apiVersion has been changed to v3

### ISSUE THREAD

**Issue by alexxa** [kubevirt/api-reference#16]
apiVersion has been changed to v3, though API docs still refer to v1. 

https://kubevirt.io/api-reference/master/definitions.html#_v1alpha1_datavolumesource

**Comment by rmohr** [comment]
@alexxa thanks for reporting.

**Comment by rmohr** [comment]
Ok, that are the CDI datasources. I think they are still a `v1alpha1`, @aglitke right?
