### ISSUE TITLE
Add scripts which are used to generate the docs

### ISSUE THREAD

**Issue by fabiand** [kubevirt/api-reference#2]
Please add the scripts which are used to generate the docs - including some readme of how they are used - to this repository.

**Comment by lukas-bednar** [comment]
@fabiand according to @rmohr  all generation should be done in kubevirt side.
https://github.com/kubevirt-incubator/api-reference/pull/4#issuecomment-344201617

So I think there is no need to have these scripts here. do you agree ?

**Comment by fabiand** [comment]
I don't mind much where the scripts reside, and yep, I think we spoke about doing it from kubevirt repo.

**Comment by lukas-bednar** [comment]
OK, I am closing this ticket.
