### ISSUE TITLE
Add git hash or alike to docs

### ISSUE THREAD

**Issue by fabiand** [kubevirt/api-reference#5]
Please add a git hash or so to the generated docs in order to understand the current state of it.

**Comment by lukas-bednar** [comment]
@fabiand OK no problem, I just want to ask where do you want to place it?

Also I want to note here that this doc is being generated only when something was changed in openapi definition. So it doesn't get updated on every commit into kubevirt repository.

**Comment by fabiand** [comment]
I don't mind where it is placed as long as it's seen.

Maybe there is already a place for a version?

And it's fine if it's not alwys getting updated.

**Comment by rmohr** [comment]
@lukas-bednar We can just add subdirectories per tag. If master, then move it to master, if tag 0.2.0, then create a folder 0.2.0 and replace the content in there. Should be pretty easy to change in the deploy script in the core repo.

**Comment by lukas-bednar** [comment]
@rmohr OK, I will do it like that.
